### ISSUE TITLE
wp_enqueue_scripts内のjs追加

### ISSUE THREAD

**Issue by quwahiro** [inc2734/habakiri#10]
wp_enqueue_scripts内でwp_enqueue_scriptをもう一つ追加してjsを呼びだそうとしたのですが、読み込まれませんでした。これはそもそも2つ呼び出せない感じですか？

I tried to call other javascript file from wp_enqueue_scripts, But I could not call it. 
## ex.

```
        wp_enqueue_script(
            get_stylesheet(),
            get_stylesheet_directory_uri() . '/assets/dist/js/app.min.js',
            array( 'jquery' ),
            null,
            true
        );
        wp_enqueue_script(
            get_stylesheet(),
            get_stylesheet_directory_uri() . '/assets/dist/js/hoge.js',
            array( 'hoge' ),
            null,
            true
        );
```

**Comment by inc2734** [comment]
ご提示のコードだと wp_enqueue_script の第1引数が重複しているようです。これは呼び出すスクリプトの識別子にあたるので、重複していると片方しか読み込まれません。
http://wpdocs.mobile.osdn.jp/%E9%96%A2%E6%95%B0%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/wp_enqueue_script
