### ISSUE TITLE
Safariで画面をリサイズした際に、2列表示のメニューが崩れる

### ISSUE THREAD

**Issue by mekemoke** [inc2734/habakiri#17]
Safari の display:table; のバグのようなのですが（Habakiri2.5.1、Safari10.0.3で再現されます）、
幅992pxより狭くリサイズしたあとに広くリサイズすると、メニューが右側に寄ってしまいます。
（iPadの向きを横→縦→横にしたときなど）

以下のCSSを足して応急処置はできました。

```
/* Safari 6.1+ (10.0 is the latest version of Safari at this time) */
@media (max-width: 991px) and (min-color-index:0) and(-webkit-min-device-pixel-ratio:0) { @media {
	.header__content { display: block !important; }
	.header__content .header__col { width: 100%; }
}}
```

参考：http://stackoverflow.com/questions/16348489/is-there-a-css-hack-for-safari-only-not-chrome

（本当はプルリクとか送れば良いのでしょうが、よくわからないため issue にて報告いたします…）

**Comment by inc2734** [comment]
ありがとうございます！この不具合把握はしていたのですが、 Safari のバグだからどうしようもないと思って放置しておりました。解決策があったのですね。ちょっと仕事がたまっておりますので、時間があいたときに確認してマージしたいと思います。
